In [1]:
#libraries in Python
#python library is a collection of funtions and methods that allows you to perform many actions without writing your code
#Like- Numpy , Matplotlib , Pandas


In [2]:
#Numpy stands for Numerical pyhon and is the core library for numeric and scientific computing.
#It consists of multi-dimensinal array objects and a collection of routines for processing those array.

#Creating Numpy array -1) Single - dimensional Array

import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [3]:
#2)Multi-dimensional Array

import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [4]:
type(n1)

numpy.ndarray

In [5]:
type(n2)

numpy.ndarray

In [6]:
#Initializing Numpy Array
#initializing Numpy array with zeros
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [7]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
import numpy as np
n1=np.zeros((10,10))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
#Initializing Numpy array with same number

import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [10]:
#Initializing Numpy array within a range
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
n1=np.arange(50,101)

In [13]:
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
n1=np.arange(50,500,10)

In [15]:
n1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

In [16]:
#Initializing Numpy array with random numbers
n1=np.random.randint(1,100,5)
n1

array([55,  2, 97, 26, 16])

In [17]:
n1=np.random.randint(100,200,10)
n1

array([142, 170, 141, 154, 145, 161, 106, 156, 184, 146])

In [18]:
#Numpy-Shape
#Checking the shape of number arrays
n1=np.array([[1,2,3] ,[4,5,6]])
n1.shape

(2, 3)

In [19]:
n1.shape=(3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
#Joining Numpy Array

#1) vstack()-The vstack() function is used to stack arrays in sequence vertically (row wise). 
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))



array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
#2) hstack()- Stack arrays in sequence horizontally (column wise).
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))




array([10, 20, 30, 40, 50, 60])

3) column_stack()- column_stack() function is used to stack 1-D arrays as columns into a 2-D array.

n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))





In [25]:
#3) column_stack()-  function is used to stack 1-D arrays as columns into a 2-D array.

n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))



array([[10, 40],
       [20, 50],
       [30, 60]])

In [29]:
#Numpy Intersection & Difference
#1)Intersect1d -  function find the intersection of two arrays and return the sorted, unique values that are in both of the input arrays.

n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [31]:
#2)Setdiff1d- function find the set difference of two arrays and return the unique values in arr1 that are not in arr2.

n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [33]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [35]:
#Numpy Array Mathematics

#1)Addition of Numpy Arrays
n1=np.array([10,20])
n2=np.array([32,61])

np.sum([n1,n2])

123

In [38]:
np.sum([n1,n2] , axis=0)

array([42, 81])

In [40]:
np.sum([n1,n2] , axis=1)

array([30, 93])

In [46]:
#Numpy Array Mathematics
#1)Basic Addition

n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [47]:
#2)Basic Subtraction
n1=np.array([10,20,30])
n1=n1-3
n1


array([ 7, 17, 27])

In [48]:
#3)Basic Multiplication
n1=np.array([10,20,30])
n1=n1*5
n1

array([ 50, 100, 150])

In [49]:
#4)Basic Division
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [50]:
#Numpy Math Functions

#1)Mean(average)
n1=np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [51]:
#2) Median
n1=np.array([10,20,30,40,50,60])
np.median(n1)



35.0

In [52]:
#3) Standard Deviation

n1=np.array([10,20,30,40,50,60])
np.std(n1)

17.07825127659933

In [55]:
#Numpy Save & Load
#1)saveing Numpy Array
n1=np.array([10,20,30,40,50,60])
np.save('my_numpy',n1)

In [57]:
#Loading Numpy Array

n1=np.array([10,20,30,40,50,60])
np.load('my_numpy.npy')
n1

array([10, 20, 30, 40, 50, 60])